name: Sync repo
on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Sync branch
    steps:
      - name: Sync master branch
        uses: tgymnich/fork-sync@v1.2.1
        with:
          head: master
          base: master
          pr_title: 'Sync master branch'
          pr_message: 'Sync master branch to get latest commit'
      - name: Sync develop branch
        uses: tgymnich/fork-sync@v1.2.1
        with:
          head: develop
          base: develop
          pr_title: 'Sync develop branch'
          pr_message: 'Sync develop branch to get latest commit'
